### ISSUE TITLE
pbs while running on sge? how come?!

### ISSUE THREAD

**Issue by fgeorgatos** [sfranky/qtop#43] opened 2015-09-24 15:02 UTC
```
$ ./qtop.py
Traceback (most recent call last):
  File "./qtop.py", line 16, in <module>
    from pbs import *
```

beh..

**Comment by fgeorgatos** [comment] 2015-09-24 15:09
not to solve it quickly, just reporting the issue here:

```
[fgeorgatos@ui qtop]$ watch -d './qtop.py -c|head -20'
close failed in file object destructor:
                                       sys.excepthook is missing
                                                                lost sys.stderr
[fgeorgatos@ui qtop]$ watch -d './qtop.py -c|head -20'
close failed in file object destructor:
                                       sys.excepthook is missing
                                                                lost sys.stderr
[fgeorgatos@ui qtop]$

```

**Comment by sfranky** [comment] 2015-09-24 16:13
cannot reproduce, I get:

    Traceback (most recent call last):
      File "./qtop.py", line 982, in <module>
        convert_to_yaml(scheduler, INPUT_FNs, filenames, options.write_method, commands)
      File "./qtop.py", line 921, in convert_to_yaml
        _func(file_orig, file_out, write_method)
      File "/home/sfranky/PycharmProjects/qtop/stat_maker.py", line 211, in make_stat
        tree = etree.parse(orig_file)
      File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1182, in parse
        tree.parse(source, parser)
      File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 647, in parse
        source = open(source, "rb")
    IOError: [Errno 2] No such file or directory: 'qstat.F.xml.stdout'

**Comment by sfranky** [comment] 2015-10-18 13:23
should be fixed

**Closed by sfranky** 2015-10-18 13:23 UTC
Labels: bug
